sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t amb690/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true amb690/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-eu-west-3-640742193989"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
