sudo: required
language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t amb690/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true amb690/frontend npm run test
