FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# Gives permission to cache folder
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

# npm run start
CMD ["npm", "run", "start"]